image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  REPOSITORY_URL: 829479169076.dkr.ecr.eu-west-1.amazonaws.com/motoshare/gitlab-ci-docker

before_script:
  - apk add --no-cache python py-pip
  - pip install awscli

stages:
  - publish

build:
  stage: publish
  script:
    - $(aws ecr get-login --no-include-email --region eu-west-1)
    - docker build -t $REPOSITORY_URL .
    - docker push $REPOSITORY_URL
